import { useRouter } from "next/router";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [isNum, setIsNum] = useState(false);
  const router = useRouter();
  const onClickBtn = () => {
    router.push(`/my_page`);
  };
  const onClickMenu = () => {
    setIsNum(!isNum);
    console.log("버튼 클릭", isNum);
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-2xl">테일윈드 테일윈드</h1>
        <button
          className="p-10 border-black hover:bg-gray-200"
          onClick={onClickBtn}
        >
          마이페이지로이동
        </button>
        <br />
        <button onClick={onClickMenu}>메뉴버튼</button>
        <div>상태 : {isNum}</div>
      </main>
    </div>
  );
}
